# Generated by Django 5.1 on 2024-10-31 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_onetimepayment_recurringpayment_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='next_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 12, 59, 20, 175563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='onetimepayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
