# Generated by Django 5.1 on 2024-11-01 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_recurringpayment_next_payment_date_and_more'),
        ('Projects', '0014_merge_20241020_1656'),
        ('Users', '0011_alter_certification_certification_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpayment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='project',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Users.clientprofile')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Users.freelancerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Projects.project')),
            ],
        ),
        migrations.DeleteModel(
            name='OneTimePayment',
        ),
        migrations.DeleteModel(
            name='RecurringPayment',
        ),
    ]
