# Generated by Django 5.1 on 2024-11-08 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_periodicpayment'),
        ('Projects', '0014_merge_20241020_1656'),
        ('Users', '0011_alter_certification_certification_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='periodicpayment',
            constraint=models.UniqueConstraint(fields=('freelancer', 'project'), name='unique_periodic_payment_per_project'),
        ),
    ]
