# Generated by Django 5.0.6 on 2024-09-05 19:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='country',
            field=django_countries.fields.CountryField(default='CO', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='AcademicRecord',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
