# Generated by Django 5.1.1 on 2024-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_freelancerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/defaultFreelancerProfileImage.jpg', null=True, upload_to='avatars/'),
        ),
    ]
