# Generated by Django 5.0.6 on 2024-09-10 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_certification_education_portfolio_workexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='degree_obtained',
        ),
        migrations.RemoveField(
            model_name='education',
            name='major',
        ),
        migrations.RemoveField(
            model_name='education',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='short_description',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='Users.freelancerprofile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='Users.freelancerprofile'),
        ),
    ]
