# Generated by Django 5.0.6 on 2024-09-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_degree_education_degree_obtained_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Users.language'),
        ),
    ]
