# Generated by Django 5.0.6 on 2024-09-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_freelancerprofile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Users.language'),
        ),
    ]
