# Generated by Django 5.1.1 on 2024-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_clientprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/defaultClientProfileImage.jpg', null=True, upload_to='avatars/'),
        ),
    ]
