# Generated by Django 5.0.6 on 2024-09-21 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_freelancerprofile_skills_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
