# Generated by Django 5.1 on 2024-10-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_freelancerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_name',
            field=models.CharField(max_length=255, verbose_name='Certification Name'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issue_date',
            field=models.DateField(verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuing_organization',
            field=models.CharField(max_length=255, verbose_name='Issuing Organization'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_obtained',
            field=models.CharField(max_length=255, verbose_name='Degree Obtained'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_name',
            field=models.CharField(max_length=255, verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, verbose_name='Portfolio URL'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
