# Generated by Django 5.1 on 2024-10-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_certification_certification_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
