# Generated by Django 5.1.1 on 2024-09-17 23:50

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_quill.fields.QuillField(default='ici'),
        ),
    ]
