# Generated by Django 5.1.1 on 2024-09-19 15:53

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_quill.fields.QuillField()),
                ('due_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='milestone_files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='Projects.project')),
            ],
        ),
    ]
