# Generated by Django 5.1.1 on 2024-09-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('planning', 'Planning'), ('development', 'Development'), ('review', 'Review'), ('delivery', 'Delivery'), ('documentation', 'Documentation'), ('normal', 'Normal')], default='development', max_length=20),
        ),
    ]
