# Generated by Django 5.1.1 on 2024-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_milestone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('normal', 'Normal'), ('planning', 'Planning'), ('development', 'Development'), ('review', 'Review'), ('delivery', 'Delivery'), ('documentation', 'Documentation')], default='development', max_length=20),
        ),
    ]
