# Generated by Django 5.1.1 on 2024-09-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_milestone_category_task'),
        ('Users', '0009_alter_freelancerprofile_skills_alter_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_associations', to='Users.freelancerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_associations', to='Projects.project')),
            ],
        ),
    ]
