# Generated by Django 5.1.1 on 2024-09-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_milestone_category_task'),
    ]

    operations = [
    ]
