# Generated by Django 5.1.2 on 2024-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
