# Generated by Django 5.1.2 on 2024-10-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_milestone_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(),
        ),
    ]
