# Generated by Django 4.2 on 2024-10-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_milestone_is_deleted_project_is_deleted_and_more'),
        ('Projects', '0013_alter_task_start_date'),
    ]

    operations = [
    ]
