# Generated by Django 5.1 on 2024-11-10 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0014_merge_20241020_1656'),
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportlog',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='reportlog',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reportlog',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
    ]
