# Generated by Django 5.1 on 2024-11-10 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_rename_generated_at_reportlog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlog',
            name='report_type',
        ),
    ]
