# Generated by Django 5.0.6 on 2024-09-29 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0002_remove_message_thread_rename_body_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Messaging.conversation'),
        ),
    ]
