# Generated by Django 5.0.6 on 2024-09-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0003_alter_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='created_at',
        ),
    ]
