name: Run Pytest

on:
  push:  # Se ejecuta en cada push
    branches:
      - '**'  # Todas las ramas
  pull_request:  # Se ejecuta en cada pull request
    branches:
      - '**'  # Todas las ramas

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        pytest --junitxml=report.xml  # Genera un reporte XML de los resultados
        
    - name: Upload test results
      uses: actions/upload-artifact@v3  # Cambiar v2 a v3
      with:
        name: pytest-report  # Nombre del archivo en los artefactos de GitHub
        path: report.xml  # Ruta del archivo de reporte
