name: test_Django

on:
  push:
    branches:
      - develop
      - 'develop/**'  # Para ramas que se derivan de develop
  pull_request:
    branches:
      - develop

jobs:
  test_project:
    runs-on: ubuntu-latest  # Sistema operativo en el que se ejecutará el código

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Define la versión de Python que usas en tu proyecto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings -q
